INSERT INTO document_categories (name, description, color, icon, isDefault, isActive, clientId, createdAt, updatedAt) VALUES
('Uncategorized', 'Default category for documents', '#6B7280', 'file', 1, 1, NULL, GETDATE(), GETDATE()),
('Contracts', 'Legal contracts and agreements', '#EF4444', 'file-text', 1, 1, NULL, GETDATE(), GETDATE()),
('Reports', 'Business reports and analytics', '#3B82F6', 'bar-chart', 1, 1, NULL, GETDATE(), GETDATE()),
('Policies', 'Company policies and procedures', '#10B981', 'shield', 1, 1, NULL, GETDATE(), GETDATE()),
('Templates', 'Document templates', '#F59E0B', 'copy', 1, 1, NULL, GETDATE(), GETDATE()),
('Invoices', 'Billing and invoice documents', '#8B5CF6', 'file-invoice', 1, 1, NULL, GETDATE(), GETDATE()),
('Presentations', 'Presentation slides and decks', '#6366F1', 'presentation', 1, 1, NULL, GETDATE(), GETDATE()),
('Financials', 'Financial statements and records', '#F87171', 'dollar-sign', 1, 1, NULL, GETDATE(), GETDATE()),
('HR Documents', 'Human resources related documents', '#34D399', 'users', 1, 1, NULL, GETDATE(), GETDATE()),
('Legal', 'Legal and compliance documents', '#F43F5E', 'gavel', 1, 1, NULL, GETDATE(), GETDATE()),
('Marketing', 'Marketing materials and plans', '#FBBF24', 'megaphone', 1, 1, NULL, GETDATE(), GETDATE()),
('Sales', 'Sales documents and proposals', '#3B82F6', 'shopping-cart', 1, 1, NULL, GETDATE(), GETDATE()),
('Training', 'Training and onboarding materials', '#A78BFA', 'book-open', 1, 1, NULL, GETDATE(), GETDATE()),
('Technical Docs', 'Technical documentation', '#60A5FA', 'code', 1, 1, NULL, GETDATE(), GETDATE()),
('Product', 'Product specifications and docs', '#F59E42', 'package', 1, 1, NULL, GETDATE(), GETDATE()),
('Customer', 'Customer-related documents', '#10B981', 'user', 1, 1, NULL, GETDATE(), GETDATE()),
('Operations', 'Operations and logistics', '#F472B6', 'truck', 1, 1, NULL, GETDATE(), GETDATE()),
('Compliance', 'Compliance and regulatory docs', '#F87171', 'shield-check', 1, 1, NULL, GETDATE(), GETDATE()),
('Research', 'Research papers and findings', '#818CF8', 'flask', 1, 1, NULL, GETDATE(), GETDATE()),
('Proposals', 'Business and project proposals', '#FBBF24', 'file-plus', 1, 1, NULL, GETDATE(), GETDATE()),
('Onboarding', 'Onboarding related documents', '#2563EB', 'file', 1, 1, NULL, GETDATE(), GETDATE()),
('Resumes', 'Resumes of candidates', '#6B7480', 'file', 1, 1, NULL, GETDATE(), GETDATE()),
('Others', 'Other miscellaneous documents', '#6B7280', 'file', 1, 1, NULL, GETDATE(), GETDATE());
